# Generated by Django 2.1 on 2019-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='login',
            field=models.CharField(default=1, max_length=150, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
