# Generated by Django 2.1 on 2019-06-23 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universites', '0003_universities_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='login',
        ),
        migrations.AddField(
            model_name='universities',
            name='id_auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
