# Generated by Django 2.1 on 2019-06-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='НАзвание фирмы')),
                ('legalName', models.CharField(max_length=200, verbose_name='Юридич название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=20, verbose_name='ОГРН')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Address')),
            ],
        ),
    ]
