# Generated by Django 2.1 on 2019-06-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('universites', '0002_department_direction'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Коммент')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='НАзвание фирмы')),
                ('description', models.CharField(max_length=200, verbose_name='Юридич название')),
                ('comment', models.CharField(max_length=300, verbose_name='Описание')),
                ('start_date', models.CharField(max_length=20, verbose_name='ИНН')),
                ('end_date', models.CharField(max_length=20, verbose_name='ОГРН')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Companies')),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universites.Department')),
                ('id_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universites.Direction')),
            ],
        ),
    ]
